// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR38OYFXA45TRIHA4fB35ZJyM1s7MLM3I',
    appId: '1:672199652315:web:2f12fa89ee79b612a62dfe',
    messagingSenderId: '672199652315',
    projectId: 'computingdb-8c773',
    authDomain: 'computingdb-8c773.firebaseapp.com',
    storageBucket: 'computingdb-8c773.firebasestorage.app',
    measurementId: 'G-HWQR4NQJZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAne-rQmRe2fQE8V5jaH2ewA_KIHjKY12A',
    appId: '1:672199652315:android:374d3a58ed030477a62dfe',
    messagingSenderId: '672199652315',
    projectId: 'computingdb-8c773',
    storageBucket: 'computingdb-8c773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkriFeDvR5dAo8r4gfAq3Qc2hR3uZsgU',
    appId: '1:672199652315:ios:5fbcf33e4634554fa62dfe',
    messagingSenderId: '672199652315',
    projectId: 'computingdb-8c773',
    storageBucket: 'computingdb-8c773.firebasestorage.app',
    iosBundleId: 'com.tiancode.compuvers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLkriFeDvR5dAo8r4gfAq3Qc2hR3uZsgU',
    appId: '1:672199652315:ios:dc1bd7b62574fc37a62dfe',
    messagingSenderId: '672199652315',
    projectId: 'computingdb-8c773',
    storageBucket: 'computingdb-8c773.firebasestorage.app',
    iosBundleId: 'com.example.compuvers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR38OYFXA45TRIHA4fB35ZJyM1s7MLM3I',
    appId: '1:672199652315:web:598b35485836f0fea62dfe',
    messagingSenderId: '672199652315',
    projectId: 'computingdb-8c773',
    authDomain: 'computingdb-8c773.firebaseapp.com',
    storageBucket: 'computingdb-8c773.firebasestorage.app',
    measurementId: 'G-T87MBPJ2N8',
  );
}
